services:
  asuswrt-firmware-notifier:
    image: ghcr.io/subasically/asuswrt-firmware-notifier:latest
    platform: linux/amd64
    restart: always
    environment:
      RSS_FEED_URL: "" # https://sourceforge.net/projects/asuswrt-merlin/rss?path=/RT-AX58U/Release
      NOTIFICATION_METHOD: "print" # Change to "email" or "slack" as needed
      # EMAIL_ADDRESS: "your_email@example.com"
      # SLACK_WEBHOOK_URL: ""
      CHECK_FREQUENCY: 3600 # 1 hour (use 86400 for a day)
      LOG_LEVEL: "info"
      PYTHONUNBUFFERED: "1" # added to ensure immediate log output
